---

git_repo: git@github.com:paolopaolopaolo/text-adventure.git
repo_name: text-adventure

project_name: textadventure
application_name: textadventure

git_ssh_pub_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDaMeJsrAyKLQsUPGcTPN2HF191fIwrdGmMd6lKFdsDGtsrNVrPFMZQrLigPwqFKbkOZY4yO/ohX/xSm/bNa7o43DdpVFcBkeOGKOJ+9GWYcL8XpKJBUzxJZE6TCXqY//eN+N1yU3b2QOnkQs9TBDNynsxbMQqP5LS/BmwtX8oH2ibJp7hqyu9b70H06gIWV5/yjDpykySnm5S+iG7e6QJqdlh8CHCYQ7RIBxX/8IfM7bPcqCPBapQRPtpmcscl6osifRblXEQhixwg8d7XINpaXuocv37NXni7f+w34rQbr476urMs1B2LLB4FmchLVBOiozFPEi3jSKQJnn1CXmMpDWxt3YI/m1AMoRRngrwHrF9Y/riYvxSpjy8JiQT39tRdUD9ti1SxBRXvBsYSDU25YsY4J3DIxT4rti47Gne9WqT7MUeqtX75yB45Z9S/MttN4bOzQEjT0fh5YrVlYLBOiEEwI1HyxDJtFajYZ4ahc7LZ+T51FBVmZYmjU+R6WhUWW3X2FAv+ZzRa+98OptevR7NZYPopYPOFzHKEvLN7yCsjdgion47akxkIxT8G0D+X5n4zTdIyWEzdn/x4cd8edoHgYKXPmajAMXJMU/jSK4fCbbNMbXq2nf0scqHdRRKvbdB0T7mkO4ncqVoYIEtW0Ns8j747mz952PNE3+7R9Q==
git_ssh_priv_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIJKAIBAAKCAgEA2jHibKwMii0LFDxnEzzdhxdfdXyMK3RpjHepShXbAxrbKzVa
  zxTGUKy4oD8KhSm5DmWOMjv6IV/8Upv2zWu6ONw3aVRXAZHjhijifvRlmHC/F6Si
  QVM8SWROkwl6mP/3jfjdclN29kDp5ELPUwQzcp7MWzEKj+S0vwZsLV/KB9omyae4
  asrvW+9B9OoCFlef8ow6cpMkp5uUvohu3ukCanZYfAhwmEO0SAcV//CHzO2z3Kgj
  wWqUET7aZnLHJeqLIn0W5VxEIYscIPHe1yDaWl7qHL9+zV54u3/sN+K0G6+O+rqz
  LNQdiyweBZnIS1QToqMxTxIt40ikCZ59Ql5jKQ1sbd2CP5tQDKEUZ4K8B6xfWP64
  mL8UqY8vCYkE9/bUXVA/bYtUsQUV7wbGEg1NuWLGOCdwyMU+K7YuOxp3vVqk+zFH
  qrV++cgeOWfUvzLbTeGzs0BI09H4eWK1ZWCwTohBMCNR8sQybRWo2GeGoXOy2fk+
  dRQVZmWJo1PkeloVFlt19hQL/mc0WvvfDqbXr0ezWWD6KWDzhcxyhLyze8grI3YI
  qJ+O2pMZCMU/BtA/l+Z+M03SMlhM3Z/8eHHfHnaB4GClz5mowDFyTFP40iuHwm2z
  TG16tp39LHKh3UUSr23QdE+5pDuJ3KlaGCBLVtDbPI++O5s/edjzRN/u0fUCAwEA
  AQKCAgBXYb7yEnz7IUrckcwd0jRNk7ixDm38QSS8EngDqXkKZ0j6puV1JTa+vE08
  L8MAzVLFRzqJN6fWkeA1HSzb25a6isbOMe6ePFTIN7ttaGb/g7ejulUYoEL2iWtG
  S3eDqo7zloTo8jAkMp74wSDSeE46SwpAQwWd1tPj5KiSC1iXiHAcNkUOz7LIOKtL
  cCPh2rm9oxcNJ4x4a0BIhc8RCnPjOv34vlCJSiP67IuM8kEQeumbJuMa5Jnjxi4k
  9TZ4ItQRvdLbi/XlERb0wqihsxB/PJ+5X59ik8D6JiLtxqamp8o082wqOdCTGdn0
  GEA0mrk6Wuy2Y+toqIC5MXWsjKxc2Qk5eHKSMGibXXGgNu8SjzhI0mbEY1plt5AG
  e4IwjsoqhrjAmYYnKwagasDaTcvdp9zaMZ+ZSxMnV4QSYGNkX0SyZNY8y8n9sLRT
  EEaqM7KC+NR8JF6i3CfnaK6iHgy6intQyWoTHCicbejeoZhY5nXw27QNyxHhufuC
  mUI8/fit5cEDOTOFuIeZKLT1RuOQE0NHpoLfUghNcmD78sDL4PRgom7AqIS3OseX
  YPcgzPkYM8AUGQfPgDOyr5glULSTqwQjQvM9CqDN3MiK4PXY5ZAuwUHZ6P5ErHDm
  +S/0l/NmI0yBMCNaoyOv8L4YXHltde7txWCtGWDm036hdF6dSQKCAQEA441Bt0Sl
  stgBNXXnibtHShddTwXnxDhxfZdKp9DjiyaHlBQLNW2C0BBiPt+mn92SBSTlX8md
  8TvLBi06GdchmSEzVGvfjsc2nYjpjXQPArNa/7PPXiWKMQR5mSQaa+MwapJ/P38y
  ZRo+Wh5Fvf7IOMdV+S/cZbU+7VWkckgnV2gkDYw4jcU+9lBmZYnyVPo6dNPjvU2X
  3pBYETge98AjLZqtxydRknNmiJmGPjGevP8I5Ri6Dq3kKDRWQvzyW0iMpKkDFaIC
  prsUpUcNDLkC1BexTeZBLhdYU9ehpflwOavA6RoJXh/7YleM9uIzny7UNWE6B08j
  cTXXzq+LsYystwKCAQEA9XkpXOufnUJDlSk0BgqCo5q3DSngOfrG9pi4d1kQ11XN
  nHT5Up5P9qhO8ogW5ObdGjnakY9g4KVcWascxuf/0vu3sgNv1dTBhVpDp6QGNrQk
  8jI/6ZoJ6KL34YrJ9uZa2en2bYoZewNDt8N9vtLU2kA+jmBlskzBdwVE2Rjb8+RU
  ioPDjOHYRhjdCdYsiD6TcVwp35PGlL90jqsSLmbxWgy6XKk+onbtcUu8G+Q1X6U+
  /vmE8MK4+Rx/6xCaiyXeqiaZnC6AysNzWYrbnj8l5zMBLB+50GgrpADflEWBHnET
  KqiZ/XmjyoYHKcb8VlU9Q3kxhiqtFfHU35ZAVyxiswKCAQEApP+LVDmJsOnhzoME
  9iD/K2FPvno4uVZ4LKokbxUPuZmhm6UBD6etv/LxWkfPyYHfXK2JSPCn/wDtUThA
  NfaBnUiusJtbymr3VjmtqG0saTfmVx1p0wmDb9Gf3oSISAy/0bcSX9d6kkb6SVxE
  E+WIB2u7Emo69OD8lRmRmXBqXn3cDprLczlAU1ivNxdUyXt8IbR3IY/+/FpMEYhR
  JDKFD49mTM9c3cWh5pDz/2r5gG+pYn2QhA5hLynsFrzVe41athb7bpdANufWq5We
  h8grneDkJuk8ABDbckgcJX5+esLoqd3ARykHniJ/y5Dv/4/0PhSXAC/JMlDpgCxY
  LdEkdwKCAQAxoPdt4+13W+hSBeyQtBtJfIQ50xeUYVFMlf/lkUpIXv6c/UFTJNLB
  6bFcc4s9aDeXj87S0wwhHw2Wy3Ob+1fLjjzLbspzjvo5PdCj2hOvh6hYlzQ4xH3w
  XNKE9Qx0MIp5uEWsS9lu92//fTS1GecS4R5EptSowb/zkksjIVWG78jv4Efu+dJC
  CdDWpkiGmzAwIRQOMdBaToMAPTIF06ZEMIKVLVqOekDzQP6dHPx1g/FCl6v7CUNg
  ihSKr+au708fU4KHAxfi5rUxi1NvoRDGt5crFpb4vbblB5AsaAj84JuhakkH6Enn
  LkXQenyV79HdDGmo2IP6BdSmB7imZ0DlAoIBACdhmsov4SppG0atNtUvyWzmOSpo
  9XgzxSUh0zMvm59exFwdP3GCqgXRoyc59oDfyzX+fahPHfwzfmZPkmT0DkPS/5W5
  CokmTwoWSCE9yGx5hMNhIMmEQUUsbsBn6B4mc1TTIV8iYjFhymqdSbkZ6PAPNR3C
  lP9ykc9J8CvAK3nXaiiqWXxlBizON9+ttbNWMA3Fd7N3wLSrNyBE9PE3hQtCjCzD
  3b9mT2jH+pLPN/1h3hxtHl4rfUsFC3XSwS1HYbi+7Ll8A96OFOa7b3Sb/RUDMCIp
  4zpXVuaYzhTy6H6S7orPchxFH4aC5iWL3/Kgfz5k9aFyDomuRdLqemFOhfU=
  -----END RSA PRIVATE KEY-----

