# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=100)),
                ('type', models.CharField(choices=[('EN', 'enemy'), ('NPC', 'npc'), ('PLR', 'player')], max_length=3)),
                ('attack_dmg', models.IntegerField()),
                ('spc_attack_dmg', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('mp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CNS', 'consumable'), ('KI', 'key item')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=100)),
                ('special_move', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('HP', 'HP Effect'), ('HPS', 'HP Stat Effect'), ('MP', 'MP Effect'), ('AD', 'Attack Damage Effect'), ('SAD', 'Special Attack Damage Effect')], max_length=3)),
                ('effect_magnitude', models.IntegerField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='adventure.Agent')),
            ],
        ),
    ]
