# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 04:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=100)),
                ('to_scenes', models.ManyToManyField(blank=True, related_name='from_scenes', to='adventure.Scene')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='type',
            new_name='inventory_type',
        ),
        migrations.RemoveField(
            model_name='move',
            name='special_move',
        ),
        migrations.AddField(
            model_name='inventory',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='inventory',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='inventory',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_items', to='adventure.Agent'),
        ),
        migrations.AlterField(
            model_name='move',
            name='type',
            field=models.CharField(choices=[('HP', 'HP Effect'), ('MP', 'MP Effect'), ('AD', 'Attack Damage Effect'), ('SAD', 'Special Attack Damage Effect')], max_length=3),
        ),
        migrations.AddField(
            model_name='agent',
            name='scene',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='adventure.Scene'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='found_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scene_items', to='adventure.Scene'),
        ),
    ]
