# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20160901_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='special_move',
            field=models.BooleanField(default=False),
        ),
    ]
