# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0005_auto_20160901_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='to_scenes',
            field=models.ManyToManyField(blank=True, related_name='from_scenes', to='adventure.Scene'),
        ),
    ]
