# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0009_auto_20160903_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='adventure.Story'),
        ),
        migrations.AlterField(
            model_name='story',
            name='first_scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='adventure.Scene'),
        ),
    ]
