# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0010_auto_20160904_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='adventure.Scene'),
        ),
    ]
