# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 03:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0014_auto_20160909_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='unlocking_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocking_scenes', to='adventure.Inventory'),
        ),
    ]
